### ISSUE TITLE
Implementing the `ManagedAddress` type in MVX contracts

### ISSUE THREAD

**Issue by yanliu18** [Pi-Squared-Inc/rust-demo-semantics#168]
The current examples uses `u64`/`u160` as the type for the addresses.
https://github.com/Pi-Squared-Inc/rust-demo-semantics/blob/810fb1c794cc70e70f5304b44401e7e9bbb414d3/tests/ukm-with-contract/erc_20_token.rs#L47

This does not comply with the MVX contract practices.

The address type syntax for MVX contracts are `ManagedAddress`. An [official example](https://github.com/multiversx/mx-sdk-rs/blob/2b9d402c515cefb19eba35ae1bec7f192542c828/contracts/examples/token-release/src/token_release.rs#L309): 
```rust
    fn send_tokens(
        &self,
        token_identifier: &TokenIdentifier,
        address: &ManagedAddress,
        amount: &BigUint,
    ) {
        self.tx()
            .to(address)
            .single_esdt(token_identifier, 0, amount)
            .transfer();
    }
```
while it is a 32 bytes data, referring to [this documentation](https://docs.multiversx.com/developers/data/abi/#basic-types): 
>32 byte account address: Address

However, ULM treats all [addresses as length 20 bytes](https://github.com/Pi-Squared-Inc/ulm/blob/6e9f77b14af106d0b97b05bdc1aff47b059988c9/kllvm/ulm_kllvm.h#L183). It is not likely to changes at this stage. 

Thus, the simplest solution to comply with MVX contract practice and ULM's implementation is to use `ManagedAddress` as the syntax for addresses in MVX smart contracts while implement it as a `u160`(aliasing) in the semantics.

**Comment by yanliu18** [comment]
@yzhang90 would you share your opinion?

**Comment by yzhang90** [comment]
We don't need to comply with with MVX practices at all. All we need to care is how to integrate with op-geth. When deploying contract/ call other contracts, the address should be evm-compatible, which is 20 bytes long. How hard it is to change the length of address?

**Comment by yanliu18** [comment]
The problem is the contract won't be legal, meaning that it cannot be compiled by MVX (since we are still claiming to be in MVX context). I am not sure how would you justify our semantics does-not comply with MVX practices.

**Comment by yzhang90** [comment]
Why our demo has anything to do with MVX? We just want to demonstrate the Rust semantics (and MVX just use Rust to write their contracts).  For example, the Stylus also supports using Rust to write contracts https://docs.arbitrum.io/stylus-by-example/primitive_data_types

btw, check the ulm interface, https://github.com/Pi-Squared-Inc/ulm/blob/6e9f77b14af106d0b97b05bdc1aff47b059988c9/kllvm/ulm_kllvm.h#L183
it requires the address to be 20bytes long.

**Comment by yanliu18** [comment]
Stylus is using Alloy, the rust version of solidity, which follows the rust primitives defined in Alloy. I guess, their rust contract has to comply with Alloy's practices?

Yes, the examples we used in rust semantics are using MVX's contract primitives which you would claim they are MVX contracts. 

Unless you decided to invent your own rust smart contract language? (Then we can throw away MVX's syntax.)

ULM's reference is only considering EVM which has not sufficient discussed other contracts. I guess to comply with ULM, the option might be a type cast from `ManagedAddress` to Solidity `Address` or at ULM level, there should be a conditional statement dealing with contract address difference.

**Comment by yanliu18** [comment]
To conclude the discussion after a call with @yzhang90 .
We could use the `ManagedAddress` as the syntax for addresses in MVX contracts, and implement it as an alias of `u160`, such that we could comply with MVX (can be compiled and executed by MVX VM) and ULM (who treats address as 20 bytes data and encoding contract calls as such) at the same time.  

The conclusion is updated in the issue.

**Comment by virgil-serbanuta** [comment]
Ok, a few things:

First, we kind of gave up a few weeks ago on using MX contracts. I think that the goal was changed explicitly by the higher-ups (@IljaZakharov in case he has time to confirm this) from a MX-based demo to a (more or less pure) Rust-based demo for ULM, in the same way that we currently have an IMP demo for the same thing. By this I mean that the MX part became optional, and that we should drop it if it made things harder for us.

FWIW, one of the issues (not the only one, though) for dropping this was that in the MX world token transfers happen through requests, while in the ULM world they happen through a "dance" where the caller approves an amount, and the callee calls the token contract to actually perform the transfer. We may be able to make the ULM transfers transparent to the MX code (at least when a MX contract is being called), but I am fairly certain that doing that would have made it impossible to have everything ready for the demo.

Now, if we are interested in a MX syntax (or a MX-like syntax), then we kind of have that right now, since it was easier to change what we had instead of rewriting everything. However, there are some differences, some of which are more obvious like the ManagedAddress thing you mentioned (another obvious one is that we're using u64/256 instead of BigUint; FWIW, the MX BigUint is an unlimited integer when used internally in a contract, but it's u800 when making calls).

Still, if we have the time (and we might have it), we could even wrap the u160 type in a ManagedAddress to make it look more like the MX syntax, but my personal opinion is that we should focus on making things work first in a similar way to how they work for IMP, and have as lower priority details like using the "proper" types (e.g. ManagedAddress instead of u160) or worrying about address length.

**Comment by yanliu18** [comment]
I agree with you.
We do not have follow the MX semantics at all.

It is only at the surface syntax level, depending on how BD persons or the people who will demo this project want to claim what contract language we used to demo, we need to provide them precise information.

**Comment by yanliu18** [comment]
@virgil-serbanuta I think this issue can be closed, unless you want to work on it in future?
